{% set version = "2.0.0" %}

package:
  name: mob_suite
  version: {{ version }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

source:
  #path: /Users/kirill/WORK/MOBSuiteHostRange2018/Source/mob-suite
  #url: https://github.com/phac-nml/mob-suite/archive/{{ version }}.tar.gz
  #sha256: d67d64a70615b908f599723651d44ae52367c01963795fdf07b9bcbbb3f787a0
  git_url: https://github.com/phac-nml/mob-suite.git
  git_rev: master



requirements:
  host:
    - python >=3.4,<3.7
    - pip
    - setuptools
  run:
    - python >=3.4
    - pycurl >=7.43
    - scipy >=1.1
    - numpy >=1.11
    - biopython >=1.70
    - pandas >=0.22.0
    - pytables >=3.3
    - blast
    - mash
    - circlator
    - ete3
    - qt >=5

test:
  source_files:
    - mob_suite/tests
  requires:
    - pytest

  commands:
    - "mob_typer -h"
    - "mob_recon -h"
    - "mob_hostrange -h"
    - "pytest -s mob_suite/tests/test_mobtyper.py"

about:
  home: https://github.com/phac-nml/mob-suite
  license: Apache License, Version 2.0
  summary: 'This package MOB-suite: software tools for clustering, reconstruction and typing of plasmids from draft assemblies. The MOB-suite is designed to be a modular set of tools for the typing and reconstruction of plasmid sequences from WGS assemblies.'
