{% set version = "3.0.0" %}

package:
  name: mob_suite
  version: {{ version }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

source:
  #path: /root/mob_suite/mob-suite
  #url: https://github.com/phac-nml/mob-suite/archive/{{ version }}.tar.gz
  #sha256: 221dc24eb6d98b119c25cabff5110709cd345790d9836cf5865bec9262fddc3f
  git_url: https://github.com/phac-nml/mob-suite.git
  git_rev: master

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.11.1
    - pytables >=3.3
    - pandas >=0.22.0
    - biopython >=1.70
    - pycurl >=7.43
    - scipy >=1.1
    - ete3 >=3.0
    - blast >= 2.9.0
    - mash >= 2.2.2


test:
  source_files:
    - mob_suite/tests
  requires:
    - pytest

  commands:
    - mob_typer -h
    - mob_recon -h
    - pytest -s mob_suite/tests/test_mobrecon.py
    - pytest -s mob_suite/tests/test_mobtyper.py


about:
  home: https://github.com/phac-nml/mob-suite
  license: Apache License, Version 2.0
  summary: 'This package MOB-suite: software tools for clustering, reconstruction and typing of plasmids from draft assemblies. The MOB-suite is designed to be a modular set of tools for the typing and reconstruction of plasmid sequences from WGS assemblies.'
